### ISSUE TITLE
Koans won't run if there's a dot in the file path

### ISSUE THREAD

**Issue by sckling** [matyb/java-koans#47]
From a mac, I'm trying to run the koans from my /Users/firstname.lastname/Project/java-koans/koans directory. Because of the dot in the file path (firstname.lastname) I get the following error:

```bash
Exception in thread "main" java.lang.RuntimeException: java.lang.RuntimeException: java.util.MissingResourceException: Can't find resource for bundle java.util.PropertyResourceBundle, key .lastname/Project/java-koans/koans/src/beginner/aboutkoans.java
	at com.sandwich.koan.runner.RunKoans.constructSuite(Unknown Source)
	at com.sandwich.koan.runner.RunKoans.safelyConstructSuite(Unknown Source)
	at com.sandwich.koan.runner.RunKoans.runKoans(Unknown Source)
	at com.sandwich.koan.runner.RunKoans.run(Unknown Source)
	at com.sandwich.koan.constant.ArgumentType.run(Unknown Source)
	at com.sandwich.koan.cmdline.CommandLineArgument.run(Unknown Source)
	at com.sandwich.koan.cmdline.CommandLineArgumentRunner.run(Unknown Source)
	at com.sandwich.koan.runner.AppLauncher.main(Unknown Source)
Caused by: java.lang.RuntimeException: java.util.MissingResourceException: Can't find resource for bundle java.util.PropertyResourceBundle, key .lastname/Project/java-koans/koans/src/beginner/aboutkoans.java
	at com.sandwich.util.io.classloader.DynamicClassLoader.loadClass(Unknown Source)
	... 8 more
Caused by: java.util.MissingResourceException: Can't find resource for bundle java.util.PropertyResourceBundle, key .lastname/Project/java-koans/koans/src/beginner/aboutkoans.java
	at java.util.ResourceBundle.getObject(ResourceBundle.java:450)
	at java.util.ResourceBundle.getString(ResourceBundle.java:407)
	at com.sandwich.util.io.filecompiler.CompilerConfig.getCompilationCommand(Unknown Source)
	at com.sandwich.util.io.filecompiler.FileCompilerAction.onFile(Unknown Source)
	at com.sandwich.util.io.FileOperation.operate(Unknown Source)
	at com.sandwich.util.io.filecompiler.FileCompiler.compile(Unknown Source)
	at com.sandwich.util.io.classloader.DynamicClassLoader.compile(Unknown Source)
	... 9 more
```

**Comment by matyb** [comment]
Oh boy, no shortage of surprises from variations in filesystem's :) I'll check this out tonight

**Comment by DavidWhitlock** [comment]
Hey, @matyb.  I fixed this in my fork last summer: https://github.com/DavidWhitlock/java-koans/commit/4a8c4691e41ad259d18ce8f783ab7b6f8d3d0248 (https://github.com/DavidWhitlock/java-koans/issues/8)

Let me know if you'd like to submit a pull request.

**Comment by matyb** [comment]
Ah yeah I see what you did... Looks like one of those mistakes I make when I'm short on sleep :)

**Comment by matyb** [comment]
A PR would be cool so you can be attributed with the fix

**Comment by DavidWhitlock** [comment]
Will do.

On Wed, Mar 4, 2015 at 7:28 PM, Mat Bentley <notifications@github.com>
wrote:

> A PR would be cool so you can be attributed with the fix
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/matyb/java-koans/issues/47#issuecomment-77300030>.
>



-- 
David Whitlock
Adjunct Lecturer
Portland State University

**Comment by matyb** [comment]
Thanks for the fix David. I've got it built and it tests cleanly.

sckling - chime in if this didn't fix it for you.

**Comment by sckling** [comment]
It works now! Thanks guys for the quick fix!

**Comment by DavidWhitlock** [comment]
Excellent.  Glad I could help out.
