### ISSUE TITLE
FileMonitorPolling error 

### ISSUE THREAD

**Issue by lscheepers** [matyb/java-koans#72]
We are experiencing intermittent failures while running the koans exercises:

Exception in thread "FileMonitorPolling" java.lang.IllegalArgumentException: Source path must actually exist. (U:\java-dojo\labs\01-koans\java-koans\k
oans\.idea\workspace.xml___jb_old___)
        at com.sandwich.util.io.ExistingFileAction.throwNonExistentFileError(ExistingFileAction.java:17)
        at com.sandwich.util.io.ExistingFileAction.onNew(ExistingFileAction.java:13)
        at com.sandwich.util.io.FileOperation.operate(FileOperation.java:12)
        at com.sandwich.util.io.ForEachFileAction.onDirectory(ForEachFileAction.java:10)
        at com.sandwich.util.io.FileOperation.operate(FileOperation.java:14)
        at com.sandwich.util.io.ForEachFileAction.onDirectory(ForEachFileAction.java:10)
        at com.sandwich.util.io.FileOperation.operate(FileOperation.java:14)
        at com.sandwich.util.io.FileMonitor.getFilesystemHashes(FileMonitor.java:76)
        at com.sandwich.util.io.FileMonitor.notifyListeners(FileMonitor.java:47)
        at com.sandwich.util.io.FileMonitorFactory$2.run(FileMonitorFactory.java:37)
        at java.lang.Thread.run(Unknown Source)

After restarting, it works again for a while and then this error appears again. 
This is happening on different operating systems.

**Comment by matyb** [comment]
can you tell me if youre using intellij in each env? i dont think ive teated with that at all :/

**Comment by lscheepers** [comment]
Yes, we are using intellij in each environment.
